import type { Metadata } from "next";
import "./scss/style.scss";
import '@splidejs/react-splide/css';
import CustomReduxProvider from "../redux-store/provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomReduxProvider>
          {children}
        </CustomReduxProvider>
      </body>
    </html>
  );
}
